services:
  neo4j:
    image: neo4j:5.20.0-enterprise
    container_name: neo4j
    ports:
      - 7474:7474 # browser
      - 7687:7687 # DB
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/seunghui12!@ # neo4j/neo4j
      # - NEO4J_server_memory_heap_initial__size=11900m
      # - NEO4J_server_memory_heap_max__size=11900m
      # - NEO4J_dbms_memory_pagecache_size=12100m
      # - NEO4J_dbms_memory_transaction_total_max=12100m # DB 당 트랜잭션 상한선
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4j_server_config_strict__validation_enabled=true
      - NEO4J_PLUGINS=["apoc", "apoc-extended", "graph-data-science", "genai", "graphql", "n10s"]
      # - NEO4J_PLUGINS=["bloom", ]  # 라이센스 필요하거나, 엔터프라이즈에서만 지원되는 플러그인
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*,gds.*,genai.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,algo.*,gds.*,genai.*
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      # - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/export:/var/lib/neo4j/export
      # - ./neo4j/logs:/var/lib/neo4j/logs
      - ./neo4j/plugins:/var/lib/neo4j/plugins
      # - ./neo4j/licenses:/var/lib/neo4j/licenses
